[versions]
kotlinx-io = "0.7.0"
varlen = "1.0.0"

[libraries]
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
varlen = { module = "org.chorus-oss:varlen", version.ref = "varlen" }